var completed = true;
var gpa = 3.97;
var firstName = "Lakshmi";
var lastName = "Telidevara";
var myData = 96.0;
var myData2 = 'The grade in the exam is ';
var myData3 = 'A';
var myData4 = ' and the score is ';
console.log(completed);
console.log("The GPA of " + firstName + " " + lastName + " is " + gpa);
console.log("Hi, ".concat(firstName, " ").concat(lastName, "'s GPA is ").concat(gpa));
console.log("".concat(myData2).concat(myData3).concat(myData4).concat(myData));
